.github/workflows/ci.yaml
.github/workflows/release.yaml

Taken from the quickstart.
Resolves #9 sans typos or mdbook; I'll leave that to a follow up if that's alright.
Will trigger CI as usual and trigger releases on tags.
Disclaimer: I'm not a member of any editor working group or something like that, so treat this as a complete outsider contribution :)

Add CI and release workflows

---

.github/workflows/ci.yaml

Unabashed yoink from Bevy's CI workflow (with a patch version bump).
Closes #12

Add typo checking

---

crates/bevy_undo/src/lib.rs

New CI action reveals some typos to fix.

Fix some typos now that CI shows the way!

---

CONTRIBUTING.md

(Redo of Pr, this fork is so cursed)

Add a "Before Submitting a Pr" section

---

crates/bevy_editor/Cargo.toml
crates/bevy_editor/src/main.rs

Add basic bevy app and 2d camera to main, just to have something to show after full compile.

Add basic bevy app setup to bevy_editor/main.rs

---

design-book/src/roadmap.md

We've been talking about more wishlist items in [#editor-dev today](https://discord.com/channels/691052431525675048/789987800014651412/1290065686898544742). I figured we should write them down, and I've added a few more ideas.

Add more wishlist items

---

design-book/src/roadmap.md

As discussed here: https://discord.com/channels/691052431525675048/789987800014651412/1290118509296095275
Summary of changes:
- Stage 1 is now for basic read-only capabilities
- Added a new stage 2 for basic editing capabilities
- Added transform gizmo to stage 2

Split step 1 into separate read-write steps

---

design-book/src/design-constraints.md

Prompted by discussion on [Discord](https://discord.com/channels/691052431525675048/789987800014651412/1290697160907817072).

Explain why the Bevy editor can't just be a plugin for existing tools

---

design-book/src/best-practices.md
design-book/src/design-paradigms.md
design-book/src/general-patterns.md

This is a follow-up building on #55. I think that focusing on the use of the editor for teams is important, and I have a few other things to say about interaction paradigms :)

Add more design guidelines

---

bevy_widgets/bevy_i-cant-believe-its-not-bsn/Cargo.toml
bevy_widgets/bevy_i-cant-believe-its-not-bsn/src/lib.rs

Add's Alice's helper crate for creating widgets.
Fixes #70.

Vendor Temporary helper crate for widgets

---

bevy_editor_panes/bevy_3d_viewport/src/lib.rs
crates/bevy_editor_styles/src/lib.rs
crates/bevy_pane_layout/Cargo.toml
crates/bevy_pane_layout/src/lib.rs

Just some quick work to make a target for testing the 3d viewport work.

Setup to make test work on 3d viewport possible

---

Cargo.toml
crates/bevy_infinite_grid/Cargo.toml
crates/bevy_infinite_grid/examples/simple.rs
crates/bevy_infinite_grid/src/lib.rs
crates/bevy_infinite_grid/src/render/grid.wgsl
crates/bevy_infinite_grid/src/render/mod.rs

- Add [`bevy_infinite_grid`](https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid) to the tree
- First commit is an unchanged copy of Foresight's repo, minus some files.
- Second commit ports from 0.14 to Bevy main. Mostly required-components and retained-rendering changes.
`cargo run -p bevy_infinite_grid --example simple`

Vendor `bevy_infinite_grid`

---

bevy_editor_panes/bevy_marketplace_viewer/src/lib.rs
crates/bevy_asset_preview/src/lib.rs
crates/bevy_editor_camera/src/editor_camera_2d/mod.rs
crates/bevy_editor_camera/src/lib.rs
crates/bevy_pane_layout/src/lib.rs
crates/bevy_undo/src/lib.rs

- Also yeet a commented line from #80
There's no code-quality label :(

Cleanup unnecessary `allow` attributes

---

crates/bevy_infinite_grid/examples/simple_2d.rs
crates/bevy_infinite_grid/src/render/mod.rs

`cargo run -p bevy_infinite_grid --example simple_2d`

Add 2D camera support to `bevy_infinite_grid`

---

Cargo.toml
bevy_editor_panes/bevy_2d_viewport/src/lib.rs
bevy_widgets/bevy_menu_bar/src/lib.rs
crates/bevy_editor/src/ui.rs
crates/bevy_editor_camera/examples/editor_camera_2d.rs
crates/bevy_editor_camera/src/editor_camera_2d/mod.rs
crates/bevy_infinite_grid/examples/simple.rs
crates/bevy_pane_layout/src/lib.rs
crates/bevy_pane_layout/src/ui.rs
crates/bevy_undo/examples/cube_move.rs
projects/alien_cake_addict/src/main.rs

- I had to pull some code from `bevy_pancam` to fix up the 2d editor camera now that we have `scale` again. It seems a bit less buggy now
- Might have fixed #68
- The port to required components for UI was straightforward

Update to the latest `bevy` commit

---

bevy_widgets/bevy_context_menu/src/lib.rs
crates/bevy_editor/Cargo.toml
crates/bevy_editor/src/main.rs
crates/bevy_pane_layout/Cargo.toml
crates/bevy_pane_layout/src/handlers.rs
crates/bevy_pane_layout/src/ui.rs

`run_system_cached` is vewy noice :ok_hand:

Move Pane Controls To A Context Menu

---

bevy_editor_panes/bevy_2d_viewport/Cargo.toml
bevy_editor_panes/bevy_2d_viewport/src/lib.rs
crates/bevy_editor_styles/src/lib.rs

Adjusts the styles of the panes, change clearcolor of viewport camera to utilize theme.

Adjust styles of panes

---

Cargo.toml
bevy_widgets/bevy_footer_bar/Cargo.toml
bevy_widgets/bevy_footer_bar/src/lib.rs
crates/bevy_editor/Cargo.toml
crates/bevy_editor/src/ui.rs
crates/bevy_editor_styles/src/lib.rs

Very simple addition, adds a footer crate we can use to display some simple info.

Add new crate bevy_footer_bar

---

crates/bevy_editor/Cargo.toml
crates/bevy_editor/src/main.rs
crates/bevy_pane_layout/src/lib.rs

To have something in the 2d viewport
Also has a single line change to layout code, helps with sizing issues some

Add infinite grid to 2d viewport, Add Window title

---

bevy_editor_panes/bevy_2d_viewport/src/lib.rs
bevy_editor_panes/bevy_3d_viewport/src/lib.rs
bevy_editor_panes/bevy_asset_browser/src/directory_content.rs
bevy_editor_panes/bevy_asset_browser/src/lib.rs
bevy_editor_panes/bevy_asset_browser/src/top_bar.rs
bevy_widgets/bevy_context_menu/src/ui.rs
bevy_widgets/bevy_footer_bar/src/lib.rs
bevy_widgets/bevy_menu_bar/src/lib.rs
crates/bevy_editor/src/ui.rs
crates/bevy_editor_styles/src/lib.rs
crates/bevy_pane_layout/src/lib.rs
crates/bevy_pane_layout/src/ui.rs

This should improve code clarity some.

Rework theme crate

---

bevy_widgets/bevy_scroll_box/src/lib.rs

Sorry @Atlas16A, this it was bothering me 😅

Scrollbox draggable ScrollBarHandle

---

crates/bevy_editor/src/project/cache.rs
crates/bevy_editor/src/project/mod.rs

- Fix Linux project not running
- Fix cache folder not being created
Haven't fixed the crashes reported by @Atlas16A, not sure if that's something due to my PR  
if it crash for you try using `WGPU_BACKEND=vulkan cargo run`

Linux launcher fixes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs_improvement.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/performance_regression.md

- import into main Bevy project

Import ISSUE TEMPLATE

---

README.md

- Add WARNING message
- Added instructions for beginners
- Put in order all
[My Readme](https://github.com/LoweredgamesDev/bevy_editor_prototypes)

Improvements Readme

---

bevy_editor_panes/bevy_asset_browser/src/io/mod.rs
bevy_editor_panes/bevy_asset_browser/src/ui/directory_content.rs
bevy_editor_panes/bevy_asset_browser/src/ui/nodes.rs
bevy_widgets/bevy_menu_bar/src/lib.rs

I've tested it and it works, just haven't added any actions yet

add click observers and conditions for top bar items (even logo)

---

bevy_editor_panes/bevy_asset_browser/src/io/mod.rs
bevy_editor_panes/bevy_asset_browser/src/io/task.rs
crates/bevy_editor/src/lib.rs
crates/bevy_editor/src/project/mod.rs

Fixes currently detected Clippy workspace warnings, to make CI more reliable

Fix existing clippy warnings

---

crates/bevy_infinite_grid/src/render/grid.wgsl
crates/bevy_infinite_grid/src/render/mod.rs

Fixes infinite grid's precision issues with Ray-Plane Intersection mapping

Fix infinite grid zoomout geometry

---

crates/bevy_editor_launcher/src/main.rs
crates/bevy_editor_launcher/src/ui.rs

Hi there,
I've added a notification for when a project does not exist in the list of projects.,
Before adding this, I guess the window closed or crashed

Project Does Not Exists Notification

---

bevy_editor_panes/bevy_asset_browser/src/io/mod.rs
bevy_editor_panes/bevy_asset_browser/src/ui/directory_content.rs
bevy_widgets/bevy_field_forms/examples/nickname.rs
bevy_widgets/bevy_field_forms/examples/numeric_fields.rs
crates/bevy_editor/src/project/cache.rs
crates/bevy_editor/src/project/mod.rs
crates/bevy_editor_cam/src/controller/component.rs
crates/bevy_pane_layout/src/pane_drop_area.rs
crates/bevy_proto_bsn/src/bsn_asset.rs
crates/bevy_proto_bsn/src/bsn_reflect.rs
crates/bevy_proto_bsn/src/construct.rs
crates/bevy_proto_bsn/src/construct_impls.rs
crates/bevy_undo/src/lib.rs

The expression '-value.abs()' is clearer than 'value.abs() * -1.0' for ensuring a negative number.
https://github.com/bevyengine/bevy_editor_prototypes/issues/219

Make anchor depth handling more consistent

---

README.md

Now they're real links, not text in square brackets.

Fixed links to the design book

---

bevy_editor_panes/bevy_properties_pane/src/lib.rs
crates/bevy_editor_core/src/lib.rs
crates/bevy_editor_core/src/utils.rs
crates/bevy_pane_layout/src/components.rs

Lots of boxed scenes! I had to implement that myself (easy enough) and add a little helper to make it concise

Port Properties Pane to BSN and Feathers

---

crates/bevy_editor/src/load_gltf.rs
crates/bevy_editor_core/src/actions.rs
crates/bevy_editor_core/src/keybinding.rs
crates/bevy_editor_core/src/lib.rs

Cleanup of the action keybinding code.

Rework action keybinding
