- Cargo.toml
- src/main.rs
This updates the `main` branch to use Bevy 0.14, though it does not touch the other branches. As part of this change, I also added `publish = false` to `Cargo.toml` to prevent it from accidentally being published on <https://crates.io>.
> Update to Bevy 0.14

- .github/workflows/ci.yaml
- src/lib.rs
- src/main.rs
Resolves #18 by definition when merged, haha
> Make clippy happy

- .github/workflows/book.yaml
- .github/workflows/ci.yaml
Closes #13 and closes #14.
This PR does two things:
1. Runs `mdbook build` and `mdbook test` on all commits, PRs, and anything else that triggers `cy.yaml`.
- The latter, `mdbook test`, checks that all Rust code snippets compile! Neat!
2. Runs `mdbook build` and deploys the results to GitHub Pages whenever a new commit is pushed to `main`.
> Setup `mdbook` checks and GitHub pages

- Cargo.toml
- crates/bevy_color_picker/Cargo.toml
- crates/bevy_color_picker/src/lib.rs
- crates/bevy_command_palette/Cargo.toml
- crates/bevy_command_palette/src/lib.rs
- crates/bevy_context_menu/Cargo.toml
- crates/bevy_context_menu/src/lib.rs
- crates/bevy_editor/Cargo.toml
- crates/bevy_editor_camera/Cargo.toml
- crates/bevy_editor_camera/src/lib.rs
- crates/bevy_inspector/Cargo.toml
- crates/bevy_inspector/src/lib.rs
- crates/bevy_localization/Cargo.toml
- crates/bevy_localization/src/lib.rs
- crates/bevy_menu_bar/Cargo.toml
- crates/bevy_menu_bar/src/lib.rs
- crates/bevy_panes/Cargo.toml
- crates/bevy_panes/src/lib.rs
- crates/bevy_preferences/Cargo.toml
- crates/bevy_preferences/src/lib.rs
- crates/bevy_scene_tree/Cargo.toml
- crates/bevy_scene_tree/src/lib.rs
- crates/bevy_toolbar/Cargo.toml
- crates/bevy_toolbar/src/lib.rs
- crates/bevy_tooltips/Cargo.toml
- crates/bevy_tooltips/src/lib.rs
- crates/bevy_undo/Cargo.toml
- crates/bevy_undo/src/lib.rs
- crates/bevy_widgets/Cargo.toml
- crates/bevy_widgets/src/lib.rs
* adds the lint config [from bevy's Cargo.tomls](https://github.com/bevyengine/bevy/blob/58f6fa94a2251665819ec8747287fab1ef151086/Cargo.toml#L33) including for sub-crates.
* adds a doc comment for each scaffolded add function, which is expected to be changed when a new crate is actually worked on.
closes #21
> add lint config, matching bevy's

- crates/bevy_asset_preview/Cargo.toml
- crates/bevy_asset_preview/src/lib.rs
- crates/bevy_marketplace_viewer/Cargo.toml
- crates/bevy_marketplace_viewer/src/lib.rs
(Redo of previous PR)
Adds bevy_marketplace_viewer crate built in to be ready to begin implementing the marketplace when the website is ready for it.
To be clear, this will just be for handling the connection between the editor and bevy foundation and (maybe?) additional visuals that the asset browser won't have (like a price tag widget, etc). This is a separate crate from the asset browser for ease of removal if a user wishes, ideally this is a top level crate that nothing else depends on.
Also adds a bevy_asset_preview crate, I imagine this to be a background process quietly scanning the asset folder and generating appropriate previews for assets not generally easy to display, this adds parity with the previews the marketplace will most likely have as well as making asset browsing …
> Add bevy_asset_preview and bevy_marketplace_viewer crates

- crates/bevy_pane_layout/Cargo.toml
- crates/bevy_pane_layout/src/lib.rs
Added documentation about the layout system and a reference to the blender docs, renamed the crate to better emphasize that this will only contain the layout system once BSN is available to us.
> Add Docs covering layout system, Rename bevy_panes to bevy_pane_layout

- .github/workflows/update-bevy.yaml
Addresses #29 
The cron job is run weekly every Monday midnight UTC, or can be triggered manually.
Action flow:
* Fetches the latest bevy main rev
* Logs in as the `github-actions` bot user, makes the replacement in `Cargo.toml`, commits changes
* Checks for an existing PR with the branch name `update-bevy` and the author name containing `github-actions` (exact matching here didn't quite work, not sure why)
* If the existing PR is found, it bumps it, or else a new PR is created
> Implement gh action for updating bevy periodically

- design-book/src/roadmap.md
Hey, as per @alice-i-cecile 's suggestion I'm submitting my suggestion here.
From the current docs and some mocks from the discord I haven't really seen multi-target support mentioned. I have a repo with multiple small applications and examples and it would be really nice for the editor to be able to define launch targets for them including feature flags. Kinda like how you have multiple debug targets in vscode or intelliJ.
> Added an idea for launch targets/profiles

- .github/workflows/update-bevy.yaml
Should hopefully fix the [failed job](https://github.com/bevyengine/bevy_editor_prototypes/actions/runs/11097148373).
I'm not 100% sure if we additionally have to ensure that GitHub Actions has the right level of access to the repository. (I currently don't have access to the repo settings)
> Update write permissions of bevy update job

- bevy_editor_panes/bevy_2d_viewport/Cargo.toml
- bevy_editor_panes/bevy_2d_viewport/src/lib.rs
- crates/bevy_editor/Cargo.toml
- crates/bevy_editor/src/main.rs
- crates/bevy_editor/src/ui.rs
- crates/bevy_editor_camera/src/editor_camera_2d/mod.rs
- crates/bevy_pane_layout/src/lib.rs
- Add the `Viewport 2D` pane which uses the 2d editor camera
- Change the default layout to include `Viewport 2D` instead of `Viewport 3D`
- Spawn a sprite just so we have something to see for now
- Pass picking events through the render target
- The ui image resize seems to lag a frame behind
`cargo run`
> Add 2D Viewport Pane

- bevy_widgets/bevy_context_menu/Cargo.toml
- bevy_widgets/bevy_context_menu/examples/simple.rs
- bevy_widgets/bevy_context_menu/src/lib.rs
- bevy_widgets/bevy_context_menu/src/ui.rs
- crates/bevy_editor_styles/src/lib.rs
`cargo run -p bevy_context_menu --example simple`
- Prevent the menu from getting clipped at the edge of the window
> Add Context Menu Widget

- bevy_widgets/bevy_context_menu/src/lib.rs
- bevy_widgets/bevy_context_menu/src/ui.rs
- Turns out root nodes don't always follow the rule that nodes that are spawned later are drawn on top of earlier nodes. Added a `ZIndex` offset to ensure the context menu is above the other UI.
Fixes #93
- Added a drop shadow to the context menu to help separate it from the background.
> Fix context menu not appearing + Add drop shadow

- Cargo.toml
Adding this allows the editor UI to work better under `wayland` without weird `xwayland` rendering glitches / issues.
This partially fixes the issues in #91 since fullscreen windows now render correctly. The pane glitching is not fixed by this tho
> Add bevy wayland feature

- bevy_editor_panes/bevy_2d_viewport/src/lib.rs
- crates/bevy_pane_layout/src/ui.rs
- Fix the second issue in #102
- Prevent the pane header and pane header text from being squished with `flex_shrink: 0`
> Viewport node + Pane header fixes

- bevy_editor_panes/bevy_2d_viewport/src/lib.rs
- Making the position `Absolute` seems to Fix #91 :shrug: 
- Fix panic when resizing viewport pane down so the image node size becomes less than `1px`
> Fix Pane Jitter

- bevy_editor_panes/bevy_asset_browser/src/directory_content.rs
The `AssetBrowserLocation`was pointing to a non existing folder
This happend because `AssetSource::Default` is guaranty to exist even if there is no "assets" folder `AssetSource::Default` being the default value of the `AssetBrowserLocation`
> Fix `AssetBrowserLocation` crash

- Cargo.toml
Trying to test my merge powers by adding `rfd` as a dependency. This crate provides access to native file-pickers.
> Add `rfd` dependency

- crates/bevy_editor/Cargo.toml
- crates/bevy_editor/src/load_gltf.rs
- crates/bevy_editor/src/main.rs
I originally wanted to integrate this into the asset browser, but that is tricky and needs more design work.
So, instead you can:
* Press `Ctrl + L` to `L`oad a file via the native file-picker, or
* Load a file by dropping it on the window
Note: Not supported on wayland: https://github.com/rust-windowing/winit/issues/1881
if a file is loaded then the first scene in that file will be spawned.
I've replaced the default cube with a plane to it doesn't overlap with the loaded scene, and shadows are now enabled on the directional light.
- This is temporary. We shouldn't load GTLF files directly, we should import them and then we can load them from the asset browser.
- We need a way to add 'actions' to asset types in the asset browser
> Add menu item for loading GLTF files

- bevy_editor_panes/bevy_2d_viewport/src/lib.rs
- bevy_editor_panes/bevy_3d_viewport/src/lib.rs
- crates/bevy_editor_styles/src/lib.rs
The current grid colors are *darker* than the viewport background.
These are distracting and don't look great. If we look at almost any other tool or editor, like Blender or Godot, the grid lines are lighter:
Add grid line color configuration to `ViewportStyles`, and make the lines lighter and less distracting.
> Use lighter grid colors

- bevy_editor_panes/bevy_2d_viewport/src/lib.rs
- bevy_editor_panes/bevy_3d_viewport/src/lib.rs
- crates/bevy_editor_styles/src/lib.rs
- crates/bevy_infinite_grid/src/lib.rs
The current Z axis color is way too saturated and hard on the eyes, and its perceived lightness is much lower than lightness of the red axis.
In most other tools and editor, like Godot and Blender, the Z axis uses a lighter blue.
Change the axis color to a lighter blue that is close to the color used by Godot and Blender.
> Change Z axis color

- bevy_editor_panes/bevy_2d_viewport/src/lib.rs
- crates/bevy_infinite_grid/examples/simple_2d.rs
- crates/bevy_infinite_grid/src/render/grid.wgsl
The infinite grids now also scale infinitely when you zoom out!*
<sub>*Until they disintegrate due to floating point error</sub>
I've reworked the meaning of the grids `scale` value too. It now means 'world units per grid square' at the lowest scaling.
`fadeout_distance` is now also relative to the scaling.
- The transition is currently instantaneous and a bit jarring, this could be smoothed out
> Infinite scaling grid

- README.md
We currently have a lot of collaboration on [Figma](https://www.figma.com/design/fkYfFPSBgnGkhbQd3HOMsL/Bevy-Editor?node-id=90-2), and the designs are starting to become quite solid. We should link to them!
Link to the Figma doc from the README.
> Link to Figma designs

- bevy_widgets/bevy_scroll_box/src/lib.rs
When playing with ScrollBox I realize that **if the ScrollBoxContent of the ScrollBox isn't initially set**, it might be 0, thus when calculating the ScrollBar size doing a **division by zero and panicking**
> Fix scroll box crash when content has size 0

- design-book/src/SUMMARY.md
- design-book/src/glossary.md
Add a basic Glossary page. Initially based on Blender terms, changed after some discussion.
Once we decide in some basic terms we can update the whole prototype docs in a follow-up PR.
> Add basic glossary

- bevy_editor_panes/bevy_asset_browser/src/directory_content.rs
- bevy_editor_panes/bevy_asset_browser/src/lib.rs
- bevy_widgets/bevy_scroll_box/src/lib.rs
Make `ScrollBox`s refresh only when the scroll position has changed.
And `ScrollBar` refresh only if Size or scroll position changed
(Before it was refreshing every `ScrollBox` every frame)
I've also fix #123
By calling a new `scroll_to_top` function when the `AssetBrowser` content change.
This reset the scroll position of the `ScrollBox`, which automatically trigger refresh systems since the value changed :)
> Refresh scroll boxes only when necessary

- bevy_widgets/bevy_scroll_box/src/lib.rs
- crates/bevy_editor/src/lib.rs
Talking with you all about the Launcher made me realize that we need a proper way to separate between Runtime and Editor behaviours. Here is cleaner way to do this, than my old `if`, but it's essentially the same.
The `RuntimePlugin` contain the bare minimum for the game to run as a game, but more than the `bevy::app` because we might need to load/use thing that were created with the editor.
e.g. config files (once this feature is ready) that's a runtime plugin
The `EditorPlugin` contain the default editor that we want to provide. (I recon it should be relatively small and the users can then use Plugin/PluginGroups to extend his functionality.
e.g scene_inspector, asset_browser, ... 
The good thing about plugins, is that we can make them configurable, and advance users would be able to …
> Splitting runtime and editor into separate plugins

- crates/bevy_editor_launcher/examples/simple_editor.rs
Simple, adds an example so we can run to see changes without messing with cargo and separate project files just to see a change on editor side.
Run via `cargo run --example simple_editor`
> Adds an example to the launcher crate for developer sanity

- crates/bevy_asset_preview/src/lib.rs
Removes the empty line after the doc comment in `bevy_asset_preview`, fixing the failing CI.
Fixes #155.
> Remove empty line after doc comment

- crates/bevy_pane_layout/src/lib.rs
- crates/bevy_pane_layout/src/pane_drop_area.rs
Add helper functions to detect the pane drop area. These will be useful when we allow changing the layout by dragging and dropping panes around. We could eventually have something like:
https://github.com/user-attachments/assets/19e1b81a-3583-4ea5-9b10-c1c7285ce53f
This is a demo of these functions in action:
https://github.com/user-attachments/assets/f5e57042-0910-4f45-9c54-ae60e4c3fb6a
> Add `PaneDropArea` detection helper functions

- design-book/src/roadmap.md
To add the ability to make a pane full screen
To keep focus on task which is necessary and avoid any distraction
To make more space for editing for small resolution screen  
Similar behavior to blender `CTRL+space` to make active  window full screen
> Add toggleable fullscreen panes item in roadmap

- bevy_editor_panes/bevy_2d_viewport/src/lib.rs
- bevy_editor_panes/bevy_3d_viewport/src/lib.rs
- bevy_editor_panes/bevy_asset_browser/src/lib.rs
- bevy_editor_panes/bevy_asset_browser/src/ui/mod.rs
- crates/bevy_pane_layout/src/lib.rs
- crates/bevy_pane_layout/src/registry.rs
- crates/bevy_pane_layout/src/ui.rs
Before
```rs
app.add_observer(on_pane_creation)
.world_mut()
.get_resource_or_init::<PaneRegistry>()
.register("Viewport 2D", |mut commands, pane_root| {
commands.entity(pane_root).insert(Bevy2dViewport::default());
});
// Pane setup system
fn on_pane_creation(trigger: Trigger<OnAdd, Bevy2dViewport>, ... 
```
After
```rs
app.register_pane("Viewport 2D", on_pane_creation);
// Pane setup system
fn on_pane_creation(structure: In<PaneStructure>, ...
```
Where `PaneStructure` is:
```rs
/// The node structure of a pane.
pub struct PaneStructure {
/// The root of the pane.
pub root: Entity,
/// The area node. Child of the root node.
pub area: Entity,
/// The header node. Child of the area node.
pub header: Entity,
/// The content node. Child of the area node.
pub content: Entity,
}
```
> Pane registry improvements

- bevy_widgets/bevy_context_menu/src/lib.rs
- bevy_widgets/bevy_context_menu/src/ui.rs
- crates/bevy_editor_styles/src/lib.rs
The context menu bugfix from https://github.com/bevyengine/bevy_editor_prototypes/pull/143 was rather complicated. Here it is replaced with a `trigger.propagate(false);` call to prevent the right click event from bubbling up further when a context menu is opened.
I've also separated the context-menu option border-radius from general buttons and adjusted it to look right.
> Simplify context menu bugfix + option border radius adjustment

- bevy_widgets/bevy_context_menu/src/lib.rs
- bevy_widgets/bevy_context_menu/src/ui.rs
when opening the context menu, if you were holding down the right click and then hovered over a context menu option, when you'd release the right click it would execute that context menu action, that's been fixed by making the context menu spawn trigger be `Pointer<Up>` instead of `Pointer<Down>`, and also made the context menu options to trigger only on left click (primary button)
> small improvements and a "bugfix" | context menus

- bevy_widgets/bevy_i-cant-believe-its-not-bsn/src/template.rs
Fixes issues with new template macro
+ Uses fully-qualified imports in templates.
+ Adjusts tests to not use blanket imports.
+ Fixes observers.
> Fix macro imports and observer insertion

- crates/bevy_infinite_grid/src/render/mod.rs
The grid wasn't updated correctly to a more recent version of bevy main
> fix infinite grid

- Cargo.toml
- bevy_widgets/bevy_field_forms/examples/nickname.rs
- bevy_widgets/bevy_i-cant-believe-its-not-bsn/src/hierarchy.rs
- bevy_widgets/bevy_i-cant-believe-its-not-bsn/src/maybe.rs
- bevy_widgets/bevy_i-cant-believe-its-not-bsn/src/template.rs
- bevy_widgets/bevy_text_editing/src/editable_text_line.rs
- crates/bevy_bsn/src/construct_impls.rs
- crates/bevy_editor/src/lib.rs
- crates/bevy_editor_cam/src/extensions/dolly_zoom.rs
- crates/bevy_editor_cam/src/extensions/look_to.rs
- crates/bevy_editor_cam/src/input.rs
- crates/bevy_pane_layout/src/registry.rs
- crates/bevy_undo/src/lib.rs
Update bevy to the most recent commit when writing this PR
> Update bevy version

- Cargo.toml
- bevy_editor_panes/bevy_asset_browser/src/ui/top_bar.rs
- bevy_widgets/bevy_i-cant-believe-its-not-bsn/src/hierarchy.rs
- crates/bevy_bsn/src/construct.rs
- crates/bevy_editor/Cargo.toml
- crates/bevy_editor_cam/src/input.rs
- crates/bevy_editor_launcher/Cargo.toml
- crates/bevy_infinite_grid/src/render/mod.rs
- crates/bevy_pane_layout/src/handlers.rs
- crates/bevy_pane_layout/src/lib.rs
- crates/bevy_pane_layout/src/ui.rs
- Re-pin bevy to  ~~`232824c009c38ee26ad308f054bc12888f0020e9`~~ `d6725d3b1baa6a730fa6bfab1bb8f2a9e5f4716e`
- Update `thiserror` to `2.0`
- Migrate `Entity`-derefs
- Migrate to `weak_handle!`
- Migrate `ConstructTuple` bundle impl
- Migrate `PointerAction`-matches with new `Scroll`-variant.
> [!CAUTION]
>~~This won't compile because of some issues with the derive macros, yielding errors like:
`use of undeclared crate or module bevy_reflect` or `use of undeclared crate or module bevy_ecs`.~~
> ~~Possibly related to https://github.com/bevyengine/bevy/pull/17330~~
> 
> ~~The errors only seem to happen for `crates/bevy_editor_cam`.~~
>
> Fixed in https://github.com/bevyengine/bevy/commit/fb0e5c484fc254a7fe3cc21a53829b1755c4dae5
Also added temporary a workaround for the Linux …
> Migrate bevy to latest main

- bevy_editor_panes/bevy_3d_viewport/src/lib.rs
- bevy_editor_panes/bevy_3d_viewport/src/view_gizmo.rs
Add a basic view gizmo that show the 3 main axis to help keep you oriented in 3d space. Eventually I need to add picking support so we can click on an axis to snap the camera to it.
Here's a demo video of how it looks currently.
https://github.com/user-attachments/assets/41d30255-7cd1-4fe1-9750-193028af66b7
> Add a basic view gizmo

- crates/bevy_proto_bsn/src/bsn_reflect.rs
Took bevy_proto_bsn to use and had trouble deserializing assets.
As far as I can tell, `PartialReflect::reflect_clone` always returns NotImplemented. Changed the `reflect_clone` call to `to_dynamic` and things seem to work. I had to make a similar change when updating our Blenvy version to support Bevy 0.16 after being on 0.15.
> Fix Clone impl of bevy_proto_bsn's ReflectedValue

- crates/bevy_proto_bsn/src/bsn_asset.rs
Negative numbers are parsed as an Unary operation containing the negative sign (-) and the number itself, instead of just as the plain number, which resulted in negative numbers in proto_bsn assets being interpret as `BsnValue::UnknownExpr` instead of correctly as `BsnValue::Number`. This made it impossible to use negative numbers in proto_bsn assets.
> Add support for negative numbers in bevy_proto_bsn parsing

- crates/bevy_proto_bsn/src/entity_patch.rs
- crates/bevy_proto_bsn/src/retain.rs
- Fixes a bug in `EntityPatch` where scenes without inheritance would be dynamically constructed instead of statically and vice versa
- Fixes panics during scene retention when trying to despan non-existent orphans
> Fix EntityPatch and scene retention bugs in `bevy_proto_bsn`

- bevy_editor_panes/bevy_properties_pane/src/lib.rs
###Current work in Progress
Just reorganizing the Properties Panel to display more information about the selected Entity from the Scene Tree in the Properties Panel as string representations using Reflection. Early feedback welcome!
> Enhance properties pane UI with improved layout and styling for entity selection and component display

- bevy_editor_panes/bevy_3d_viewport/src/lib.rs
- crates/bevy_editor/src/lib.rs
- crates/bevy_editor_cam/src/input.rs
Picking for objects through the viewport will now behave properly, including the camera controller.
It only took 8 months! <sub> well, just one day..<sub> today.
- Assign each 3d viewport panel/camera their own custom pointer entity
- Copy every `PointerInput` event action from the mouse to these custom pointers with their location adjusted
- Rework camera input to respond to input from custom pointers
> Fix 3d viewport picking passthrough and camera input

- crates/bevy_pane_layout/src/lib.rs
Now selecting an entity doesn't annihilate the layout because of the properties panel overflowing!
> Fix panel layout exploding when panels overflow

- crates/bevy_editor/src/lib.rs
- crates/bevy_editor/src/load_gltf.rs
Reminder that you can drag & drop gltf/glb files onto the editor to load them *(broken on wayland)*, or press `ctrl+L` to open a file picker.
> Allow loading gltf/glb files from outside the assets directory

- bevy_editor_panes/bevy_3d_viewport/src/selection_box.rs
- bevy_editor_panes/bevy_properties_pane/src/lib.rs
- bevy_editor_panes/bevy_scene_tree/src/lib.rs
- crates/bevy_editor/src/lib.rs
- crates/bevy_editor_core/src/lib.rs
- crates/bevy_editor_core/src/selection.rs
- crates/bevy_editor_core/src/utils.rs
- Moved selection code to its own module
- Added helper methods to `SelectedEntity`, and some observer system handlers
- Made the plane selectable by clicking it in the scene
- Hacked together the excellently named `Pointer<DragCancelClick>` event. It only responds to clicks without pointer movement to prevent double interactions with draggable entities, or camera controllers.
> Improve selection

- crates/bevy_editor/src/load_gltf.rs
- crates/bevy_editor_core/src/actions.rs
- crates/bevy_editor_core/src/lib.rs
This adds a registry of 'actions', also known as [commands](https://code.visualstudio.com/api/ux-guidelines/command-palette) in VS Code, or [operators](https://docs.blender.org/manual/en/4.5/interface/operators.html) in Blender.
There's also rudimentary support for keyboard shortcuts.
> Humble Beginnings for the `ActionRegistry`

- bevy_editor_panes/bevy_2d_viewport/src/lib.rs
- bevy_editor_panes/bevy_3d_viewport/src/lib.rs
- bevy_editor_panes/bevy_3d_viewport/src/view_gizmo.rs
- crates/bevy_editor/src/lib.rs
- crates/bevy_pane_layout/src/components.rs
- crates/bevy_pane_layout/src/lib.rs
- crates/bevy_pane_layout/src/ui.rs
- This also sets the winit `UpdateMode` to 'reactive' at 60hz to reduce power draw on systems with high refresh-rate displays
- There are some `.insert(Node::default())` sprinkled together with `spawn_scene` because of some bug where child UI nodes might not appear otherwise.
> Port Viewport Panes to BSN and Feathers

- design-book/src/SUMMARY.md
- design-book/src/styles.md
The current placeholder icon set, Lucide, isn't currently documented. 
I added a page to the design book to help contributors find the font (and, in the future, discover other design choices in the Editor).
- Added a new page to the design book (`styles.md`)
- Stuck that into the mdBook `SUMMARY.md`
- Added a section about the current font (Lucide)
I used `mdbook serve` and checked out my changes - they seem to work just fine! :)
> Document the Lucide placeholder icon font

- bevy_editor_panes/bevy_3d_viewport/Cargo.toml
- bevy_editor_panes/bevy_3d_viewport/src/lib.rs
- crates/bevy_editor/Cargo.toml
- crates/bevy_editor/src/lib.rs
- crates/bevy_editor_cam/src/controller/component.rs
- crates/bevy_editor_cam/src/input.rs
- crates/bevy_transform_gizmos/src/lib.rs
- Follows up on #236, doing the final fix-ups needed to get the transform gizmo working within the 3d viewport.
I chose to remove the 2d circle mesh for now as it gets in the way of picking despite being invisible in the 3d viewport, and the workaround gets annoying here.
Added a box to and tweaked the scene so it's a little more interesting.
Known issue: The editor cam can anchor onto the gizmo (rather than the scene entities behind it). Would require something like per pointer filters for picking, or perhaps the mesh picking backend could optionally try to check whether a mesh is visible to some camera.
> Transform Gizmo
